# Generated by Django 4.1.5 on 2023-01-24 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('version_release', models.IntegerField(default=0)),
                ('version_patch', models.IntegerField(default=0)),
                ('version_feature', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
